# Sets the URL name of the quickstart on public I/O (required)
slug: otel-collector-data-flow

# Displayed in the UI (required)
title: OpenTelemetry Collector Data Flow

# Long-form description of the quickstart (required)
description: |
  The OpenTelemetry Collector Data Flow quickstart contains a dashboard that helps visualize the flow of data through the collector, monitor the collector's performance, and identify telemetry bottlenecks. The dashboard includes performance metrics related to the telemetry pipeline, such as the number of metrics, logs, and traces processed, refused, and dropped. Also included are CPU and Memory consumption, and stats related to the batch processor.

# Displayed in search results and recommendations. Summarizes a quickstarts functionality.
summary: |
  The OpenTelemetry Collector Data Flow quickstart contains a dashboard that helps visualize the flow of data through the collector, monitor the collector's performance, and identify telemetry bottlenecks.

# Support level: New Relic | Verified | Community (required)
level: Community

# Authors of the quickstart (required)
authors:
  - Brad Schmitt

# Keywords for filtering / searching criteria in the UI
keywords:
  - OpenTelemetry
  - OTel
  - Collector
  - Prometheus

# Reference to alert policies to be included in this quickstart
# alertPolicies:
#   - condition-a
#   - condition-b

# Reference to dashboards to be included in this quickstart
dashboards:
  - otel-collector-data-flow

# Documentation references
documentation:
  - name: OpenTelemetry Collector Internal Telemetry
    url: https://opentelemetry.io/docs/collector/internal-telemetry/#basic-level-metrics
    description: OpenTelemetry documentation for the collector internal telemetry.

# Content / Design
icon: logo.svg
