id: opentelemetry
displayName: OpenTelemetry
description: OpenTelemetry is an open-source framework that collects, processes, and exports telemetry data from applications and infrastructure.
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/opentelemetry/opentelemetry-introduction/
keywords:
  - opentelemetry
  - otel
  - collector
icon: logo.svg
