# Sets the URL name of the quickstart on public I/O (required)
slug: template

# Displayed in the UI (required)
title: Account Security Health

# Long-form description of the quickstart (required)
description: |
  This dashboard can be used to review your New Relic account audit activity to ensure your New Relic usage remains compliant with your organizational policies and expectations.

# Displayed in search results and recommendations. Summarizes a quickstarts functionality.
summary: |
  An example New Relic account security audit dashboard.

# Support level: New Relic | Verified | Community (required)
level: New Relic

# Authors of the quickstart (required)
authors:
  - Alec Isaacson

# Keywords for filtering / searching criteria in the UI
keywords:
  - security
  - audit
  - health

# Reference to dashboards to be included in this quickstart
dashboards:
  - account-security-health

# Content / Design
icon: logo.png